[programs.localnet]
<<<<<<< HEAD
up_token = "HHP6PWv5APf8fS1cTGcZyYcbKfGL4KFYVoLM1Xzoc5Uw"

[programs.devnet]
up_token = "HHP6PWv5APf8fS1cTGcZyYcbKfGL4KFYVoLM1Xzoc5Uw"
=======
up_token = "Up111111111111111111111111111111111111111"
>>>>>>> 1b3568e9557a0d186e14cc8b4511fe3aaf270877

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
<<<<<<< HEAD

[toolchain]
anchor_version = "0.32.1"
=======
>>>>>>> 1b3568e9557a0d186e14cc8b4511fe3aaf270877
