[programs.localnet]
up_token = "HHP6PWv5APf8fS1cTGcZyYcbKfGL4KFYVoLM1Xzoc5Uw"

[programs.devnet]
up_token = "HHP6PWv5APf8fS1cTGcZyYcbKfGL4KFYVoLM1Xzoc5Uw"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[toolchain]
anchor_version = "0.32.1"