[package]
name = "up_token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "up_token"

[features]
<<<<<<< HEAD
default = []
no-entrypoint = []
cpi = ["no-entrypoint"]


[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
anchor-spl  = { version = "0.32.1", features = ["token_2022", "associated_token"] }
thiserror   = "1.0"
=======
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["token", "associated_token"] }
solana-program = "1.18.23"
spl-token-2022 = "4.0.0"
thiserror = "1.0"
>>>>>>> 1b3568e9557a0d186e14cc8b4511fe3aaf270877
